#ifndef	F4SEVRSCENEGRAPH_VERSION_INCLUDED
#define F4SEVRSCENEGRAPH_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define F4SEVRSCENEGRAPH_VERSION_MAJOR	1
#define F4SEVRSCENEGRAPH_VERSION_MINOR	0
#define F4SEVRSCENEGRAPH_VERSION_PATCH	0
#define F4SEVRSCENEGRAPH_VERSION_BETA	0
#define F4SEVRSCENEGRAPH_VERSION_VERSTRING	MAKE_STR(F4SEVRSCENEGRAPH_VERSION_MAJOR) "." MAKE_STR(F4SEVRSCENEGRAPH_VERSION_MINOR) "." MAKE_STR(F4SEVRSCENEGRAPH_VERSION_PATCH) "." MAKE_STR(F4SEVRSCENEGRAPH_VERSION_BETA)

#endif
